baseURL: https://mingyanwebsite.netlify.app/
googleAnalytics: UA/G-123123-12
languageCode: en-us
enableEmoji: yes
theme: avicenna
title: MingYan
paginate: 10
markup:
  tableOfContents:
    endLevel: 3
    ordered: no
    startLevel: 1
params:
  name: MingYan
